[application]
name = "theldo"

[web.app]

# HTML title tag content
title = "theldo"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[mounts]
  source = "theldo.db"
  destination = "/usr/local/app/theldo.db"

[bundle]
publisher = "Ajian Labs"
identifier = "com.ajianlabs"
